[package]
name = "hnefatafl"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
easy-ml = { git = "https://github.com/Skeletonxf/easy-ml" } # 1.9 isn't out yet
clap = { version = "4", features = [ "derive" ] }
rustyline = "9.0"


[build-dependencies]
cbindgen = "0.24"
