[package]
name = "hnefatafl"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
easy-ml = { git = "https://github.com/Skeletonxf/easy-ml" } # 1.9 isn't out yet
structopt = "0.3"
rustyline = "9.0"
uniffi = "0.21"
uniffi_macros = "0.21.0"

[build-dependencies]
uniffi_build = "0.21"
# cbindgen = "0.24"
