// Generated by jextract

package io.github.skeletonxf.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor hello_from_rust$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle hello_from_rust$MH = RuntimeHelper.downcallHandle(
        "hello_from_rust",
        constants$0.hello_from_rust$FUNC
    );
}


